export const LOAD_STATIONS = 'LOAD_STATIONS';
export const LOAD_STATIONS_SUCCESSFULLY = 'LOAD_STATIONS_SUCCESSFULLY';
export const LOAD_STATIONS_ERROR = 'LOAD_STATIONS_ERROR';
export const SELECT_STATION = 'SELECT_STATION';